title: "Продление аренды в Дубае через RDC"
description: "Практический гайд по RERA, Offer & Deposit, Tableegh и Lease Renewal Claim"
lang: ru-RU

theme: minima

url: "https://sanex3339.github.io"
baseurl: "/dubai-apartment-renewal-story"
